ALTER TABLE studios ADD COLUMN ttlock_lock_id BIGINT DEFAULT NULL COMMENT 'TTLock Lock ID';
ALTER TABLE bookings ADD COLUMN ttlock_passcode VARCHAR(20) DEFAULT NULL COMMENT 'TTLock 臨時密碼';
ALTER TABLE bookings ADD COLUMN ttlock_passcode_id BIGINT DEFAULT NULL COMMENT 'TTLock keyboardPwdId';
